version: '3'
services:
  auth_db:
    image: redis
    command: redis-server --requirepass 'password'
    ports:
      - '6379:6379'
    volumes:
      - redis_volume:/var/lib/redis/data

volumes:
  redis_volume:
    driver: local
